# Generated by Django 3.2.12 on 2022-04-14 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_proj', models.CharField(max_length=64, unique=True)),
                ('repo_proj', models.URLField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_or_close', models.BooleanField(default=True)),
                ('text_proj', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('todo_proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.projects')),
            ],
        ),
    ]
