# Generated by Django 3.2.12 on 2022-04-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='active_or_close',
            field=models.BooleanField(default=True),
        ),
    ]
